server.port=8081
spring.application.name=wallet-microservice
spring.main.banner-mode=console
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.sql.init.mode=never
# Schema file is available but initialization is manual now
spring.sql.init.schema-locations=classpath:ddl/schema.sql
spring.sql.init.encoding=UTF-8
spring.jpa.show-sql=true
logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG
logging.file.name=wallet-app.log